name: hardware_info_kit
description: A Flutter plugin for retrieving hardware information across multiple platforms. Get CPU, memory, GPU, disk, battery, and OS information easily.
version: 1.0.0
homepage: https://github.com/h1s97x/HardwareInfoKit
repository: https://github.com/h1s97x/HardwareInfoKit
issue_tracker: https://github.com/h1s97x/HardwareInfoKit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.hardware_info_kit
        pluginClass: HardwareInfoKitPlugin
      windows:
        pluginClass: HardwareInfoKitPlugin
